export {
  fetchData,
  postData,
  patchData,
  deleteData,
  postImage,
  postImages,
} from './methods';
export type {
  User,
  ProductCategory,
  Product,
  Review,
  AuthResponse,
  CartResponse,
  CartsResponse,
  IdResponse,
  MinMaxResponse,
  ProductsResponse,
  AddProduct,
  CategoriesResponse,
  UserStatistics,
  ProductStatistics,
  CartStatistics,
  Statistics,
} from './entity.types';
